# Generated by Django 4.1.6 on 2024-03-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0002_checkin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('moment_number', 'user_id', 'date')},
        ),
    ]
