# Generated by Django 4.1.6 on 2024-03-18 17:07

import datetime
from django.db import migrations, models
from django.utils import timezone

def convert_times_to_datetimes(apps, schema_editor):
    User = apps.get_model('JP_Django', 'User')
    for obj in User.objects.all():
        obj.time1 = timezone.now().replace(hour=obj.time1.hour, minute=obj.time1.minute)
        obj.time2 = timezone.now().replace(hour=obj.time2.hour, minute=obj.time2.minute)
        obj.time3 = timezone.now().replace(hour=obj.time3.hour, minute=obj.time3.minute)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0003_alter_checkin_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 8, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 15, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time3',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 0)),
        ),
        migrations.RunPython(convert_times_to_datetimes),
    ]
