# Generated by Django 4.1.6 on 2024-04-03 12:33

import datetime
from django.db import migrations, models

def convert_date_to_datetime(apps, schema_editor):
    Checkin = apps.get_model('JP_Django', 'Checkin')
    for obj in Checkin.objects.all():
        obj.date = datetime.datetime.now().replace(day=obj.date.day, month=obj.date.month, year=obj.date.year)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0006_checkin_content_checkin_text_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='header',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 8, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 15, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time3',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 21, 0)),
        ),
        migrations.RunPython(convert_date_to_datetime),
    ]
