# Generated by Django 4.1.6 on 2024-04-05 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0007_checkin_header_alter_checkin_date_alter_user_time1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 8, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 15, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time3',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 21, 0)),
        ),
    ]
