# Generated by Django 4.1.6 on 2024-04-05 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0008_user_current_streak_user_longest_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('user_id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('one_day', models.BooleanField(default=False)),
                ('one_week', models.BooleanField(default=False)),
                ('one_month', models.BooleanField(default=False)),
                ('one_year', models.BooleanField(default=False)),
            ],
        ),
    ]
