# Generated by Django 4.2 on 2024-04-16 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0013_remove_checkin_header_alter_user_time1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='communityuser',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
