# Generated by Django 4.2 on 2024-04-18 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0014_community_date_created_communityuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuser',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 8, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 15, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time3',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 0)),
        ),
    ]
