# Generated by Django 4.2 on 2024-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JP_Django', '0016_checkin_privacy_alter_user_time1_alter_user_time2_and_more'),
        ('JP_Django', '0017_prompt_alter_user_time1_alter_user_time2_and_more'),
    ]

    operations = [
    ]
