# Generated by Django 4.2 on 2024-07-25 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JP_Django", "0017_prompt_alter_user_time1_alter_user_time2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time1",
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 8, 0)),
        ),
        migrations.AlterField(
            model_name="user",
            name="time2",
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 15, 0)),
        ),
        migrations.AlterField(
            model_name="user",
            name="time3",
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 21, 0)),
        ),
    ]
