# Generated by Django 4.1.6 on 2024-02-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JpdUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(db_column='first_Name', max_length=100)),
                ('last_name', models.CharField(db_column='last_Name', max_length=100)),
                ('email', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'jpd_User',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
