# Generated by Django 4.1.6 on 2024-02-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
