# Generated by Django 4.1.6 on 2024-02-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
