# Generated by Django 4.1.6 on 2024-02-17 22:38

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0002_jpduser_delete_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jpduser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
