# Generated by Django 4.1.6 on 2024-02-21 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time1',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='time2',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='time3',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
    ]
