# Generated by Django 4.1.6 on 2024-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
