# Generated by Django 4.1.6 on 2024-02-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0003_alter_jpduser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jpduser',
            managers=[
            ],
        ),
    ]
