# Generated by Django 4.1.6 on 2024-03-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewish_Positivity_Django', '0005_user_id_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='user_id',
        ),
    ]
