name: Django CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * 1,3,5'
    - cron: '0 9 * * 1,3,5'
    - cron: '0 12 * * 1,3,5'
    - cron: '0 16 * * 1,3,5'
    - cron: '0 21 * * 1,3,5'
    - cron: '0 8 * * 0,2,4,6'
    - cron: '0 12 * * 0,2,4,6'
    - cron: '0 16 * * 0,2,4,6'
    - cron: '0 21 * * 0,2,4,6'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        cd Django
        python manage.py test