name: Django CI

on: push

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DJ_KEY: ${{ secrets.DJ_KEY }}
        run: |
          cd JP_Django
          python manage.py test JP_Django.tests.test_views.CreateUserViewTestCase
          python manage.py test JP_Django.tests.test_views.SetTimesViewTestCase
          python manage.py test JP_Django.tests.test_views.UpdateUserInfoViewTestCase
          python manage.py test JP_Django.tests.test_views.GetTimesViewTestCase
          python manage.py test JP_Django.tests.test_views.GetUserInformationViewTestCase
          python manage.py test JP_Django.tests.test_views.CheckinViewTestCase
          python manage.py test JP_Django.tests.test_views.GetCheckinsViewTestCase
          python manage.py test JP_Django.tests.test_views.AddFriendViewTestCase
          python manage.py test JP_Django.tests.test_views.GetFriendsViewTestCase
          python manage.py test JP_Django.tests.test_views.DeleteFriendViewTestCase
          python manage.py test JP_Django.tests.test_views.DeleteUserViewTestCase
          python manage.py test JP_Django.tests.test_views.UpdateStreakTestCase
          python manage.py test JP_Django.tests.test_views.GetProfilePictureViewTestCase
