name: Django CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 1,3,5'
    - cron: '0 14 * * 1,3,5'
    - cron: '0 17 * * 0,1,2,3,4,5,6'
    - cron: '0 23 * * 0,1,2,3,4,5,6'
    - cron: '0 2 * * 0,1,2,3,4,5,6'
    - cron: '0 13 * * 0,2,4,6'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        cd Django
        python manage.py test Jewish_Positivity_Django.tests.test_views.CreateUserViewTestCase
