name: Build and Deploy to TestFlight

on:
  workflow_dispatch:  # Allows manual triggering
  # You can also keep other triggers if you want
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'  # Specify the Ruby version you need

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: |
          cd ios
          if [ -f "Podfile" ]; then
            pod install
          fi
          cd ..

      - name: Resolve Package Dependencies
        run: |
          cd ios
          if [ -f "JewishPositivity.xcworkspace" ]; then
            xcodebuild -resolvePackageDependencies -workspace JewishPositivity.xcworkspace -scheme JewishPositivity -derivedDataPath ../DerivedData
          else
            xcodebuild -resolvePackageDependencies -project JewishPositivity.xcodeproj -scheme JewishPositivity -derivedDataPath ../DerivedData
          fi
          cd ..

      - name: Build and Upload to TestFlight
        run: bundle exec fastlane ios beta
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}